name: Builderino
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows_lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy the executable to the artifact directory
        run: cp ./Build/PhysicsGame ./artifact

      - name: Upload artifact
        run: actions/upload-artifact@v4
      
